server.modules = (
  "mod_accesslog",
  "mod_rewrite"
)

server.document-root = "/var/www/localhost/htdocs"
server.bind = "0.0.0.0"
server.port = 8080
server.errorlog = "/proc/self/fd/2"

accesslog.filename = "/proc/self/fd/1"
index-file.names = ("index.html")

mimetype.assign = (
  ".css" => "text/css; charset=utf-8",
  ".gif" => "image/gif",
  ".html" => "text/html; charset=utf-8",
  ".ico" => "image/x-icon",
  ".jpeg" => "image/jpeg",
  ".jpg" => "image/jpeg",
  ".js" => "text/javascript; charset=utf-8",
  ".json" => "application/json; charset=utf-8",
  ".map" => "application/json; charset=utf-8",
  ".png" => "image/png",
  ".svg" => "image/svg+xml",
  ".txt" => "text/plain; charset=utf-8",
  ".webp" => "image/webp",
  ".woff2" => "font/woff2"
)

url.rewrite-if-not-file = (
  "" => "/index.html"
)
